version: 2.1
executors:
  dotnetcoreexecutor:
    docker:
      - image: microsoft/aspnetcore-build:2.2
jobs:
  build:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test