version: 2
executors:
  dotnetcoreexecutor:
    docker:
      - image: microsoft/dotnet:2.2-sdk
jobs:
  build:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: dotnet build Source/ProtoStar.Core.csproj
  test:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: dotnet test
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
        requires:
          - build